### ISSUE TITLE
Business logic in controller?

### ISSUE THREAD

**Issue by Jalalx** [fals/cqrs-clean-eventual-consistency#2]
Hello.
Just saw your comment on [Clean Architecture with ASP.NET Core 2.1
](https://www.youtube.com/watch?v=_lwCVE_XgqI&lc=UgybpKNC7Kd7prmNau94AaABAg) and came here to say I can't agree more! 😄  

I see you're having business login inside your controller. Is it ok? Shouldn't it, for example, just throws a `NotFoundException` in the application layer and translated to `HTTP 404` by a middleware?

https://github.com/fals/cqrs-clean-eventual-consistency/blob/dfa62994bd1608c766be209e19a00a7807b8fb4b/src/Ametista.Api/Controllers/CardController.cs#L65-L68

**Comment by fals** [comment]
Hey I appreciate your feedback! I'm going to answer you with another question. 

If you change the ASP.NET Web API, which is a technology detail, where clients to acknowledge their requests, depending on a HTTP response fallowing the REST standards  stated at [rfc6690](https://tools.ietf.org/html/rfc6690) how should you respond to them? 

The user interface is not business, its a technology detail. You could change this example to use a console application, and instead of sending BadRequest, which is REST, you could print if the command/query wasn't successful, "Wrong command, fix your input". 

My example, as I stated is not a perfect domain focused, I just tried to translate CQRS to clean.  You can find a better and awesome domain focused example here: [Manga](https://github.com/ivanpaulovich/clean-architecture-manga)

Also, there's **The Null Object pattern**, I found a good implementation in the book [Adaptive Code](https://www.amazon.de/Adaptive-Code-patterns-principles-Practices/dp/1509302581/), and you could create a generic way to handle this anywhere, with any UI, but always in a particular way, because every interface behaves differently from each other. 

 CQRS Itself is complicated, I hadn't enough time to implement every good pattern, but I would love to see some PR's fixing what I got wrong :D!!

**Comment by fals** [comment]
Closing this issue, I think the question was answered.
