### ISSUE TITLE
Events are not persisted, thus no audit

### ISSUE THREAD

**Issue by maxpavlov** [fals/cqrs-clean-eventual-consistency#3]
In the readme, your state that the read database can be reconstructed from write DB, but that is not true. In your demo, you seem to store an entity instead of events related to that entity, and thus write db and read db are almost the same. It seems to me this validated the essence and removes the event sourcing part that is crucial here. CQRS is retained though.

**Comment by fals** [comment]
@maxpavlov I've never mentioned or tried to implement ES there. It's common to mistake EDA (Event Driven Architecture) with ES (Event Sourcing). You don't need ES to implement CQRS. You can add ES to your aggregates if you want, but it will just create more complexity, and wasn't my goal with this implementation, CQRS is very complex and ES just adds more complexity. My budy has a good example of ES here, you can take a look: [https://github.com/ivanpaulovich/event-sourcing-jambo](event-sourcing-jambo)

I recommend you take a look at this article from Vaughn Vernon about ES https://kalele.io/to-event-source-or-not/ as well.

Regarding the databases, they are not the same at all. The Query database has a very specific model, if you look at the materialization you will see some aggregation and denomarlization going on. Maybe because the model is simple, and most of the fields coincide you had an impression that they are the same.
