### ISSUE TITLE
What am I missing here

### ISSUE THREAD

**Issue by PeterJD** [fals/cqrs-clean-eventual-consistency#7]
Hi
Followed your instruction but no docker instruction or RabbitQ.Client errors on TryConnect

So what are  we missing here?
Is your documentation up todate?
Are you adding Blazor front end ?
Kind regards
Peter

**Comment by fals** [comment]
@PeterJD what exactly is the problem? You will notice that the connection will fail few times, because Rabbit is starting but the service didn't start yet, you can put a `restart: always` in the API section in the docker-composer, so the service will retry to get up until all the infrastructure is ready.

Regarding the front-end, I have no intention to add it back, I'm trying to focus on the backend :).

**Comment by PeterJD** [comment]
will reply soon but have had a system crash I use iMac for win 10. Who knows how long this will take, thankfully I created a system image.

**Comment by fals** [comment]
@PeterJD this project runs in any platform, you can just install Docker on your MacOS and run the commands to spin it up

**Comment by PeterJD** [comment]
Hi fals
Transferred Bootcamp to SSD was a experience not to forget, used Winclone which was problematic.
tried your app started no issues, shall now investigate your project, 
Disappointed you decided not to implement Blazor
sound like a slow hard drive, may have caused the issue
Peter
